async def mctpd_mctp_base_iface_obj(dbus):
    obj = await dbus.get_proxy_object(
        'au.com.codeconstruct.MCTP1', '/au/com/codeconstruct/mctp1'
    )
    return await obj.get_interface('au.com.codeconstruct.MCTP1')


async def mctpd_mctp_iface_obj(dbus, iface):
    obj = await dbus.get_proxy_object(
        'au.com.codeconstruct.MCTP1',
        '/au/com/codeconstruct/mctp1/interfaces/' + iface.name,
    )
    return await obj.get_interface('au.com.codeconstruct.MCTP.BusOwner1')


async def mctpd_mctp_iface_control_obj(dbus, iface):
    obj = await dbus.get_proxy_object(
        "au.com.codeconstruct.MCTP1",
        "/au/com/codeconstruct/mctp1/interfaces/" + iface.name,
    )
    return await obj.get_interface("au.com.codeconstruct.MCTP.Interface1")


async def mctpd_mctp_endpoint_obj(dbus, path, iface):
    obj = await dbus.get_proxy_object(
        'au.com.codeconstruct.MCTP1',
        path,
    )
    return await obj.get_interface(iface)


async def mctpd_mctp_network_obj(dbus, net):
    obj = await dbus.get_proxy_object(
        'au.com.codeconstruct.MCTP1',
        f'/au/com/codeconstruct/mctp1/networks/{net:d}',
    )
    iface = await obj.get_interface('au.com.codeconstruct.MCTP.Network1')
    # fixup autogenerated snake-case names
    iface.get_local_eids = iface.get_local_ei_ds
    iface.set_local_eids = iface.set_local_ei_ds
    return iface


async def mctpd_mctp_endpoint_control_obj(dbus, path):
    return await mctpd_mctp_endpoint_obj(
        dbus, path, 'au.com.codeconstruct.MCTP.Endpoint1'
    )


async def mctpd_mctp_endpoint_common_obj(dbus, path):
    return await mctpd_mctp_endpoint_obj(
        dbus, path, 'xyz.openbmc_project.MCTP.Endpoint'
    )
